/* Generated by tools/gen_overlay_assets.py. Do not edit.
 * Regenerate from the repo root: python tools/gen_overlay_assets.py
 */
#pragma once

#include <stdint.h>

typedef struct {
    uint16_t w, h;
    uint32_t alpha_len;
    uint32_t zlen;
    const uint8_t *z;
    uint16_t red_x, red_y, red_w, red_h;
    const uint8_t *red_a;
} ov_rose_asset_t;

typedef struct {
    uint16_t w, h;
    const uint16_t *rgb565;
    const uint8_t *a4;
} ov_rain_asset_t;

extern const ov_rose_asset_t ov_rose_asset;
extern const ov_rain_asset_t ov_rain_asset;
