/* Generated by tools/gen_overlay_assets.py. Do not edit.
 * Regenerate from the repo root: python tools/gen_overlay_assets.py
 */
#pragma once

#include <stdint.h>

typedef struct {
    uint16_t cp;
    uint8_t w, h, adv;
    int8_t xoff, yoff;
    uint32_t off;
} ov_glyph_t;

typedef struct {
    uint8_t px, ascent, descent;
    uint16_t n;
    const ov_glyph_t *glyphs;
    const uint8_t *bits;
} ov_font_t;

extern const ov_font_t ov_fonts[];
extern const int ov_font_n;
